<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.2.6 on 2023-10-29 13:31

from django.db import migrations
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
# Generated by Django 4.2.6 on 2023-10-29 13:31

from django.db import migrations
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394


class Migration(migrations.Migration):

<<<<<<< HEAD
<<<<<<< HEAD
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
=======
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
    dependencies = [
    ]

    operations = [
<<<<<<< HEAD
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
    ]
