<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-29 13:00
=======
# Generated by Django 4.2.6 on 2023-10-28 11:19
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('favorite_books', models.TextField(blank=True, null=True)),
                ('favorite_author', models.TextField(blank=True, null=True)),
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
