# Generated by Django 4.2.6 on 2023-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_profile_favorite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
