# Generated by Django 4.2.6 on 2023-10-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_alter_profile_favorite_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
