# Generated by Django 4.2.6 on 2023-10-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(verbose_name="{%static 'images/profile.jpg'%}"),
        ),
    ]
