# Generated by Django 4.2.6 on 2023-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.TextField(blank=True, null=True)),
                ('Book-Title', models.TextField(blank=True, null=True)),
                ('Book-Author', models.TextField(blank=True, null=True)),
                ('Year-Of-Publication', models.PositiveIntegerField(blank=True, null=True)),
                ('Publisher', models.TextField(blank=True, null=True)),
                ('Image-URL-S', models.URLField(blank=True, null=True)),
                ('Image-URL-M', models.URLField(blank=True, null=True)),
                ('Image-URL-L', models.URLField(blank=True, null=True)),
                ('Rating', models.FloatField(default=0)),
                ('Reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
