# Generated by Django 4.2.6 on 2023-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20231027_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
