<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-27 08:52
=======
# Generated by Django 4.2.6 on 2023-10-28 04:01
>>>>>>> e1910658457b3de8f52218fe2137cc813aff1de3

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('landing_page', '0002_auto_20231026_1102'),
=======
        ('landing_page', '0002_auto_20231027_2316'),
>>>>>>> e1910658457b3de8f52218fe2137cc813aff1de3
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
