# Generated by Django 4.2.6 on 2023-10-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_bookreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Book-Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Image-URL-L',
            new_name='image_url_l',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Image-URL-M',
            new_name='image_url_m',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Image-URL-S',
            new_name='image_url_s',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Book-Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Rating',
            new_name='total_ratings',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Reviews',
            new_name='total_reviews',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Year-Of-Publication',
            new_name='year',
        ),
    ]
