# Generated by Django 4.2.5 on 2023-10-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_bookreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
