# Generated by Django 4.2.6 on 2023-10-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
