# Generated by Django 4.2.6 on 2023-10-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_rename_book_author_books_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='total_upvote',
            new_name='total_upvotes',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
