# Generated by Django 4.2.6 on 2023-10-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0005_rename_isbn_books_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewbuku', models.TextField(blank=True, null=True)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('gambar_url_m', models.URLField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.books')),
            ],
        ),
    ]
