# Generated by Django 4.2.6 on 2023-10-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers_favorite', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readersfavorite',
            old_name='user_comments',
            new_name='user_comment',
        ),
    ]
